# [build]
# functions = "netlify-functions"
# command = "vite build"

[[redirects]]
# Redirect all other routes to index.html
from = "/*"
to = "/index.html"
status = 200

# Environment variables for all branches
[build.environment]
NODE_OPTIONS = "--max_old_space_size=4096"

# Network
DAPP_NETWORK = "mainnet"

# API URLs
XX_API_URL = 'wss://rpc.xx.network'

# Explorer URLs
XX_EXPLORER_URL = 'https://explorer.xx.network'

# Indexer URLs
XX_INDEXER_URL = 'https://indexer.xx.network/'
ETH_INDEXER_URL = 'https://bridge-backend.xx.network/indexer'

# Address of the XX network contract
WRAPPED_XX_ADDRESS = '0x171120219d3223e008558654ec3254a0f206edb2'

# Address of the Ethereum network contract
BRIDGE_ERC20_HANDLER_ADDRESS = '0x2297db5f1775cdea3e9696e00a005996129283d8'

# Address of the Bridge contract
BRIDGE_ADDRESS = '0x104977989515b040879226f293eacbf342f39ab7'

# Address of the Relayer
BRIDGE_RELAYER_FEE_ADDRESS = '0x6e398fd37a69a417287cdbb1b0cfa41b63e03762'

########################
# Sepolia Testnet
########################
[context.sepolia.environment]

# Network
DAPP_NETWORK = "sepolia"

# API URLs
XX_API_URL = 'wss://bridge-sepolia.xx.network/xx/rpc'

# Explorer URLs
XX_EXPLORER_URL = 'https://explorer.xx.network'
ETH_EXPLORER_URL = 'https://sepolia.etherscan.io'

# Indexer URLs
XX_INDEXER_URL = 'https://bridge-sepolia.xx.network/xx/indexer'
ETH_INDEXER_URL = 'https://bridge-sepolia.xx.network/eth/indexer'

# Address of the XX network contract
WRAPPED_XX_ADDRESS = '0x777878005e784C7832565242cdC31f730C7A2Ba8'

# Address of the Ethereum network contract
BRIDGE_ERC20_HANDLER_ADDRESS = '0x3f3Dd3167B6a6CA2bBC8b8E1f322D27B3eA66754'

# Address of the Bridge contract
BRIDGE_ADDRESS = '0xA76bfbAD22a7769BF282649341f7B26adFa6e1A0'

# Address of the Relayer
BRIDGE_RELAYER_FEE_ADDRESS = '0xEBF3262497FAa76cB609EB8b477dA7Ccb45C9039'


########################
# Bridge Devnet
########################
[context.dev.environment]

# Network
DAPP_NETWORK = "dev"

# API URLs
XX_API_URL = 'wss://bridge-dev.xx.network/xx/rpc'
ETH_API_URL = 'https://bridge-dev.xx.network/eth/rpc'

# Explorer URLs
XX_EXPLORER_URL = 'https://explorer.xx.network'
ETH_EXPLORER_URL = 'https://devnet.routescan.io'

# Indexer URLs
XX_INDEXER_URL = 'https://bridge-dev.xx.network/xx/indexer'
ETH_INDEXER_URL = 'https://bridge-dev.xx.network/eth/indexer'

# Address of the XX network contract
WRAPPED_XX_ADDRESS = '0x3f709398808af36ADBA86ACC617FeB7F5B7B193E'

# Address of the Ethereum network contract
BRIDGE_ERC20_HANDLER_ADDRESS = '0x3167776db165D8eA0f51790CA2bbf44Db5105ADF'

# Address of the Bridge contract
BRIDGE_ADDRESS = '0x62877dDCd49aD22f5eDfc6ac108e9a4b5D2bD88B'

# Address of the Relayer
BRIDGE_RELAYER_FEE_ADDRESS = '0x028152c03ad5E28dE97AEaf90f104C7eD42a47bB'
